# Generated by Django 2.1.7 on 2019-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newSite', '0002_auto_20190319_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='teste',
            field=models.CharField(default='teste', max_length=255),
        ),
    ]
